on:
  push:
    branches:
    - main
jobs:
  myjob:
    name: deploy to staging
    runs-on:  windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0   
      - name: Install Dependencies
        run: npm install
  
